// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1V4hBK9F8EWLmILl_8MZ_43EQ7_l3HkY',
    appId: '1:613330144242:web:eac5274970b5c8e7ef396b',
    messagingSenderId: '613330144242',
    projectId: 'banco-test-91e94',
    authDomain: 'banco-test-91e94.firebaseapp.com',
    storageBucket: 'banco-test-91e94.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUNyg7ns5nLy9vyyIp-2XwOiZ3Hh6Hdo8',
    appId: '1:613330144242:android:98ed6aade7b6fc00ef396b',
    messagingSenderId: '613330144242',
    projectId: 'banco-test-91e94',
    storageBucket: 'banco-test-91e94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPineh8TlU8WbXHZC4SjjjXP13rGV9PFQ',
    appId: '1:613330144242:ios:1c5c3f2eae403d14ef396b',
    messagingSenderId: '613330144242',
    projectId: 'banco-test-91e94',
    storageBucket: 'banco-test-91e94.firebasestorage.app',
    iosBundleId: 'com.example.tuFondo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPineh8TlU8WbXHZC4SjjjXP13rGV9PFQ',
    appId: '1:613330144242:ios:1c5c3f2eae403d14ef396b',
    messagingSenderId: '613330144242',
    projectId: 'banco-test-91e94',
    storageBucket: 'banco-test-91e94.firebasestorage.app',
    iosBundleId: 'com.example.tuFondo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1V4hBK9F8EWLmILl_8MZ_43EQ7_l3HkY',
    appId: '1:613330144242:web:ae1060f489d16837ef396b',
    messagingSenderId: '613330144242',
    projectId: 'banco-test-91e94',
    authDomain: 'banco-test-91e94.firebaseapp.com',
    storageBucket: 'banco-test-91e94.firebasestorage.app',
  );
}
